#!/usr/bin/env bash
# =============================================================================
# 00_freeze_versions.sh — Record exact commit SHAs for all cloned repos
# =============================================================================
# Run this once after 01_clone_repos.sh to snapshot the versions you measured.
# Writes stack_lock.yaml, which 01_clone_repos.sh reads on subsequent runs
# to pin every clone to the same commit.
#
# Usage:
#   ./00_freeze_versions.sh          # freeze all selected repos
#   ./00_freeze_versions.sh --all    # include alternatives too
#
# Output:
#   stack_lock.yaml   one entry per repo: sha, date, tag (if any)
# =============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/stack_config.yaml"
REPOS_DIR="$SCRIPT_DIR/repos"
LOCK_FILE="$SCRIPT_DIR/stack_lock.yaml"
FREEZE_ALL=false

[[ "${1:-}" == "--all" ]] && FREEZE_ALL=true

for cmd in python3 git; do
    command -v "$cmd" &>/dev/null || { echo "ERROR: $cmd not found" >&2; exit 1; }
done
python3 -c "import yaml" 2>/dev/null || {
    echo "ERROR: PyYAML not installed (pip install pyyaml)" >&2; exit 1
}

MANIFEST=$(STACK_CONFIG="$CONFIG" python3 -c "
import os, yaml
layers = ['data_pipelines', 'training', 'integration_serving', 'cross_cutting']
cfg = yaml.safe_load(open(os.environ['STACK_CONFIG']))
for layer in layers:
    for p in cfg.get(layer, {}).get('projects', []):
        print(f\"{layer}\t{p.get('repo','')}\t{p.get('status','')}\")
")

echo "# stack_lock.yaml — pinned commit SHAs for reproducible measurement"  > "$LOCK_FILE"
echo "# Generated by 00_freeze_versions.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$LOCK_FILE"
echo "# Do not edit manually. Re-run 00_freeze_versions.sh to refresh."       >> "$LOCK_FILE"
echo "#"                                                                        >> "$LOCK_FILE"
echo "# To reproduce the exact measurement:"                                   >> "$LOCK_FILE"
echo "#   1. Run 01_clone_repos.sh  (reads this file, checks out pinned SHAs)" >> "$LOCK_FILE"
echo "#   2. Run 02_measure_loc.sh"                                            >> "$LOCK_FILE"
echo "#   3. Run 03_count_deps.sh"                                             >> "$LOCK_FILE"
echo "#   4. Run 04_aggregate.py"                                              >> "$LOCK_FILE"
echo "repos:"                                                                  >> "$LOCK_FILE"

found=0
missing=0
failed=0

while IFS=$'\t' read -r layer repo status; do
    [[ "$FREEZE_ALL" == false && "$status" == "alternative" ]] && continue

    project_name=$(basename "$repo")
    target_dir="$REPOS_DIR/$layer/$project_name"

    if [[ ! -d "$target_dir/.git" ]]; then
        printf "  %-45s  NOT CLONED — skipping\n" "$repo"
        missing=$((missing+1))
        continue
    fi

    sha=$(git -C "$target_dir" rev-parse HEAD 2>/dev/null || echo "")
    if [[ -z "$sha" ]]; then
        printf "  %-45s  ERROR: could not read SHA\n" "$repo"
        failed=$((failed+1))
        continue
    fi

    date_str=$(git -C "$target_dir" log -1 --format="%ci" HEAD 2>/dev/null | cut -d' ' -f1 || echo "")
    tag=$(git -C "$target_dir" tag --points-at HEAD 2>/dev/null | head -1 || echo "")

    printf "  %-45s  %s  %s\n" "$repo" "$sha" "${date_str}"

    {
        echo "  - repo: $repo"
        echo "    layer: $layer"
        echo "    sha: $sha"
        [[ -n "$date_str" ]] && echo "    date: $date_str"
        [[ -n "$tag"      ]] && echo "    tag: $tag"
    } >> "$LOCK_FILE"

    found=$((found+1))
done <<< "$MANIFEST"

echo ""
echo "════════════════════════════════════════════════════════════════"
printf "  Pinned : %d repos\n"  "$found"
[[ "$missing" -gt 0 ]] && printf "  Missing: %d repos (not yet cloned)\n" "$missing"
[[ "$failed"  -gt 0 ]] && printf "  Errors : %d repos\n" "$failed"
echo "  Output : $LOCK_FILE"
echo "════════════════════════════════════════════════════════════════"
