#!/usr/bin/env bash
# =============================================================================
# 02_measure_loc.sh — Measure lines of code for each cloned repository
# =============================================================================
# Usage: ./02_measure_loc.sh [--all]
#   --all  include "alternative" repos (must have been cloned with --all)
#
# Prerequisites: run 01_clone_repos.sh first.
# Requirements:  scc >= 3  (https://github.com/boyter/scc), jq, python3+PyYAML
#
# What is measured:
#   - Code lines only (excludes blank lines and comments)
#   - Generated code excluded via --no-gen (vendored/autogenerated files)
#   - Only repos with a .clone_ok marker (successfully cloned)
#   - Only "selected" repos by default; add --all to include alternatives
#
# Known scope limitation:
#   This script measures LOC of the 48 top-level repos (direct dependencies).
#   Transitive dependencies (the packages *they* depend on) are NOT measured
#   here — that is the job of 03_count_deps.sh.  The transitive
#   count is expected to be 10-100x larger and is the key number for the
#   supply-chain-size argument in the paper.
#
# Outputs:
#   results/loc_per_project/      per-project scc JSON files (one per repo)
#   results/loc_summary.csv       summary table (layer, project, LOC, files, langs, COCOMO $M)
#   results/loc_report.tsv        append-log across runs (same style as clone_report.tsv)
#   results/loc_summary.txt       human-readable summary with totals
# =============================================================================

set -uo pipefail   # no -e: failures handled per-repo

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/stack_config.yaml"
REPOS_DIR="$SCRIPT_DIR/repos"
RESULTS_DIR="$SCRIPT_DIR/results"
LOC_DIR="$RESULTS_DIR/loc_per_project"
MEASURE_ALL=false
START_TS=$(date +%s)

[[ "${1:-}" == "--all" ]] && MEASURE_ALL=true

# ── dependency check ──────────────────────────────────────────────────────────
for cmd in scc jq python3; do
    command -v "$cmd" &>/dev/null || { echo "ERROR: $cmd not found" >&2; exit 1; }
done
python3 -c "import yaml" 2>/dev/null || {
    echo "ERROR: PyYAML not installed (pip install pyyaml)" >&2; exit 1
}
# scc version check (need >= 3 for --no-gen)
scc_ver=$(scc --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+' | head -1 || echo "0.0")
scc_major=$(echo "$scc_ver" | cut -d. -f1)
if [[ "$scc_major" -lt 3 ]]; then
    echo "WARN: scc version $scc_ver detected; >= 3 recommended for --no-gen support" >&2
fi

mkdir -p "$RESULTS_DIR" "$LOC_DIR"

# ── parse YAML once: layer<TAB>repo<TAB>status<TAB>role ──────────────────────
MANIFEST=$(STACK_CONFIG="$CONFIG" python3 -c "
import os, yaml
layers = ['data_pipelines', 'training', 'integration_serving', 'cross_cutting']
cfg = yaml.safe_load(open(os.environ['STACK_CONFIG']))
for layer in layers:
    for p in cfg.get(layer, {}).get('projects', []):
        role = p.get('role', '').replace('\t', ' ').replace('\n', ' ')
        print(f\"{layer}\t{p.get('repo','')}\t{p.get('status','')}\t{role}\")
")

# ── output files ──────────────────────────────────────────────────────────────
CSV="$RESULTS_DIR/loc_summary.csv"
REPORT_TSV="$RESULTS_DIR/loc_report.tsv"

printf "layer,project,repo,status,code_lines,comment_lines,blank_lines,files,cocomo_cost_musd,languages\n" > "$CSV"
if [[ ! -f "$REPORT_TSV" ]]; then
    printf "timestamp\tstatus\tlayer\trepo\tcode_lines\tfiles\tcocomo_musd\treason\n" > "$REPORT_TSV"
fi

# ── counters ──────────────────────────────────────────────────────────────────
measured_count=0
skip_count=0
fail_count=0
current=0
FAILED_REPOS=()
FAILED_REASONS=()
LAYERS=("data_pipelines" "training" "integration_serving" "cross_cutting")

# ── pre-count ─────────────────────────────────────────────────────────────────
total=0
while IFS=$'\t' read -r _l _r status _role; do
    [[ "$MEASURE_ALL" == false && "$status" == "alternative" ]] && continue
    total=$((total+1))
done <<< "$MANIFEST"

# ── graceful interrupt ────────────────────────────────────────────────────────
INTERRUPTED=false
trap 'INTERRUPTED=true; echo ""' INT TERM

# ── helpers ───────────────────────────────────────────────────────────────────
ts()  { date "+%H:%M:%S"; }
pad() { printf "%0${#total}d" "$1"; }

log_row() {
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" "$2" "$3" "$4" "$5" "$6" "$7" \
        >> "$REPORT_TSV"
}

fmt_loc() {   # format large numbers with commas via python
    python3 -c "print(f'{int(\"$1\"):,}')" 2>/dev/null || echo "$1"
}

# ── header ────────────────────────────────────────────────────────────────────
echo "Config  : $CONFIG"
echo "Repos   : $REPOS_DIR"
echo "Scope   : $total repos  (all=$MEASURE_ALL)"
echo "Note    : measuring direct deps only; transitive deps are out of scope here"
echo "────────────────────────────────────────────────────────────────────"

# ── layer totals (accumulated) ────────────────────────────────────────────────
declare -A layer_code
declare -A layer_files
for layer in "${LAYERS[@]}"; do
    layer_code[$layer]=0
    layer_files[$layer]=0
done
grand_code=0
grand_files=0
grand_cocomo=0   # in thousands USD, accumulated as integer cents of MUSD

# ── main loop ─────────────────────────────────────────────────────────────────
current_layer=""

while IFS=$'\t' read -r layer repo status role; do
    [[ "$INTERRUPTED" == true ]] && break
    [[ "$MEASURE_ALL" == false && "$status" == "alternative" ]] && continue

    if [[ "$layer" != "$current_layer" ]]; then
        echo ""
        echo "▶ $layer"
        current_layer="$layer"
    fi

    current=$((current+1))
    project_name=$(basename "$repo")
    target_dir="$REPOS_DIR/$layer/$project_name"
    marker="$target_dir/.clone_ok"
    out_json="$LOC_DIR/${layer}__${project_name}.json"

    # ── not cloned / incomplete ───────────────────────────────────────────────
    if [[ ! -f "$marker" ]]; then
        printf "  [%s/%d] %s  ⚠ skip     %s  (not cloned or incomplete)\n" \
            "$(pad $current)" "$total" "$(ts)" "$repo"
        skip_count=$((skip_count+1))
        log_row "skipped_not_cloned" "$layer" "$repo" "0" "0" "0" "no .clone_ok marker"
        continue
    fi

    # ── already measured: use cached result ───────────────────────────────────
    if [[ -f "$out_json" ]]; then
        code=$(jq '[.[] | .Code]    | add // 0' "$out_json")
        files=$(jq '[.[] | .Count]  | add // 0' "$out_json")
        cocomo=$(jq '[.[] | .cocomo // 0] | add // 0' "$out_json" 2>/dev/null || echo 0)
        printf "  [%s/%d] %s  ✓ cached   %-38s  %s lines\n" \
            "$(pad $current)" "$total" "$(ts)" "$repo" "$(fmt_loc "$code")"
        measured_count=$((measured_count+1))
        layer_code[$layer]=$(( layer_code[$layer] + code ))
        layer_files[$layer]=$(( layer_files[$layer] + files ))
        grand_code=$((grand_code + code))
        grand_files=$((grand_files + files))
        log_row "cached" "$layer" "$repo" "$code" "$files" "$cocomo" ""
        # still write to CSV
        langs=$(jq -r '[.[] | select(.Code > 0) | .Name] | join(";")' "$out_json")
        comment=$(jq '[.[] | .Comment] | add // 0' "$out_json")
        blank=$(jq   '[.[] | .Blank]   | add // 0' "$out_json")
        echo "$layer,$project_name,$repo,$status,$code,$comment,$blank,$files,$cocomo,\"$langs\"" >> "$CSV"
        continue
    fi

    # ── measure ───────────────────────────────────────────────────────────────
    printf "  [%s/%d] %s  ⏱ measuring %-36s\n" \
        "$(pad $current)" "$total" "$(ts)" "$repo"

    repo_start=$(date +%s)
    err_file=$(mktemp)

    # --no-gen: exclude generated/vendored files (protobuf outputs, etc.)
    if scc --format json --no-gen "$target_dir" > "$out_json" 2>"$err_file"; then

        code=$(jq  '[.[] | .Code]    | add // 0' "$out_json")
        comment=$(jq '[.[] | .Comment] | add // 0' "$out_json")
        blank=$(jq   '[.[] | .Blank]   | add // 0' "$out_json")
        files=$(jq '[.[] | .Count]   | add // 0' "$out_json")
        cocomo=$(jq '[.[] | .cocomo // 0] | add // 0' "$out_json" 2>/dev/null || echo 0)
        langs=$(jq -r '[.[] | select(.Code > 0) | .Name] | join(";")' "$out_json")
        elapsed=$(( $(date +%s) - repo_start ))

        printf "  [%s/%d] %s  ✓ ok       %-38s  %s lines  (%ds)\n" \
            "$(pad $current)" "$total" "$(ts)" "$repo" "$(fmt_loc "$code")" "$elapsed"

        measured_count=$((measured_count+1))
        layer_code[$layer]=$(( layer_code[$layer] + code ))
        layer_files[$layer]=$(( layer_files[$layer] + files ))
        grand_code=$((grand_code + code))
        grand_files=$((grand_files + files))

        echo "$layer,$project_name,$repo,$status,$code,$comment,$blank,$files,$cocomo,\"$langs\"" >> "$CSV"
        log_row "success" "$layer" "$repo" "$code" "$files" "$cocomo" ""

    else
        if [[ "$INTERRUPTED" == true ]]; then
            printf "  [%s/%d] %s  ⚡ stopped  %s\n" \
                "$(pad $current)" "$total" "$(ts)" "$repo"
            rm -f "$out_json" "$err_file"
            break
        fi
        reason=$(tr '\n' ' ' < "$err_file" | sed 's/  */ /g; s/^ //; s/ $//')
        printf "  [%s/%d] %s  ✗ failed   %s\n" \
            "$(pad $current)" "$total" "$(ts)" "$repo"
        printf "             └─ %s\n" "$reason"
        fail_count=$((fail_count+1))
        FAILED_REPOS+=("$repo")
        FAILED_REASONS+=("$reason")
        rm -f "$out_json"
        log_row "failed" "$layer" "$repo" "0" "0" "0" "$reason"
    fi
    rm -f "$err_file"

done <<< "$MANIFEST"

# ── summary ───────────────────────────────────────────────────────────────────
ELAPSED=$(( $(date +%s) - START_TS ))
ELAPSED_FMT=$(printf "%02d:%02d:%02d" $((ELAPSED/3600)) $((ELAPSED%3600/60)) $((ELAPSED%60)))
SUMMARY="$RESULTS_DIR/loc_summary.txt"

print_summary() {
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "  LOC Measurement — $(date)"
    echo "════════════════════════════════════════════════════════════════════"
    printf "  %-22s %d / %d\n" "Measured:"    "$measured_count" "$total"
    printf "  %-22s %d\n"      "Skipped:"     "$skip_count"
    printf "  %-22s %d\n"      "Failed:"      "$fail_count"
    printf "  %-22s %s\n"      "Elapsed:"     "$ELAPSED_FMT"
    echo ""

    # Per-layer totals
    echo "  Code lines by layer (excl. generated):"
    printf "  %-28s  %12s  %8s\n" "Layer" "Code lines" "Files"
    printf "  %-28s  %12s  %8s\n" "─────────────────────────────" "──────────" "──────"
    for layer in "${LAYERS[@]}"; do
        printf "  %-28s  %12s  %8s\n" \
            "$layer" \
            "$(fmt_loc "${layer_code[$layer]}")" \
            "$(fmt_loc "${layer_files[$layer]}")"
    done
    printf "  %-28s  %12s  %8s\n" "─────────────────────────────" "──────────" "──────"
    printf "  %-28s  %12s  %8s\n" "TOTAL (direct deps only)" \
        "$(fmt_loc "$grand_code")" "$(fmt_loc "$grand_files")"
    echo ""

    # Top repos by LOC
    echo "  Largest repos by code lines (top 10):"
    if [[ -f "$CSV" ]]; then
        # skip header, sort by code_lines col (5), descending
        tail -n +2 "$CSV" | sort -t, -k5 -rn | head -10 | \
            while IFS=, read -r _layer _proj _repo _status code _com _bl _files _coc _langs; do
                printf "  %14s  %s\n" "$(fmt_loc "$code")" "$_repo"
            done
    fi
    echo ""

    # Language breakdown across all repos
    echo "  Languages present (top 15 by total code lines):"
    if ls "$LOC_DIR"/*.json &>/dev/null; then
        jq -r '.[] | "\(.Name)\t\(.Code)"' "$LOC_DIR"/*.json 2>/dev/null \
            | awk -F'\t' '{lang[$1]+=$2} END {for (l in lang) print lang[l], l}' \
            | sort -rn | head -15 \
            | while read -r loc lang; do
                printf "  %14s  %s\n" "$(fmt_loc "$loc")" "$lang"
            done
    fi
    echo ""

    # Scope reminder
    echo "  ⚠  Scope: direct dependencies only ($(fmt_loc "$grand_code") lines across $total repos)."
    echo "     Transitive dependencies are NOT included here — see 03_count_deps.sh."
    echo "     Expected transitive count: 10-100x more packages, likely 10-50x more LOC."
    echo ""

    # Failures
    if [[ ${#FAILED_REPOS[@]} -gt 0 ]]; then
        echo "  Failed repos:"
        for i in "${!FAILED_REPOS[@]}"; do
            printf "    ✗ %s\n"    "${FAILED_REPOS[$i]}"
            printf "      └─ %s\n" "${FAILED_REASONS[$i]}"
        done
        echo ""
    fi

    if [[ "$INTERRUPTED" == true ]]; then
        echo "  ⚡ Run interrupted. Re-run to resume (cached .json files are reused)."
        echo ""
    elif [[ "$current" -lt "$total" ]]; then
        echo "  ⚠  $((total - current)) repos not yet reached. Re-run to continue."
        echo ""
    fi

    echo "  Outputs:"
    echo "    $CSV"
    echo "    $LOC_DIR/  (per-project JSON)"
    echo "    $REPORT_TSV"
    echo "    $SUMMARY"
    echo "════════════════════════════════════════════════════════════════════"
}

print_summary | tee "$SUMMARY"
